### ISSUE TITLE
20170608

### ISSUE THREAD

**Issue by daninfpj** [caneco/design-tips#4]
Aesome project! Please, keep them coming!

However I think this one is a bit off: https://design-tips.caneco.xyz/20170608/

In the [original tip](https://twitter.com/steveschoger/status/872865304719892480) the text color is the same in the refactored version, and only the icon color changes to a slightly lighter color. You changed both so in the refactored version icon color is still the same as the text.

**Comment by caneco** [comment]
Thanks for the notice! Didn't realise that entirely before you mentioned :)

It's fixed.
